/* Extracted from the HTML prototype (v6.7) */

export const INDUSTRIES = [
  { id: 'all', n: 'All Functions', ico: '⚡' },
  { id: 'Finance', n: 'Finance', ico: '📊' },
  { id: 'HR', n: 'HR', ico: '👥' },
  { id: 'Marketing', n: 'Marketing', ico: '📱' },
  { id: 'Sales', n: 'Sales', ico: '💼' },
  { id: 'Operations', n: 'Operations', ico: '⚙️' },
  { id: 'IT', n: 'IT', ico: '💻' },
  { id: 'Product', n: 'Product', ico: '🎯' },
  { id: 'Strategy', n: 'Strategy', ico: '🔍' },
  { id: 'SCM', n: 'Supply Chain', ico: '🔗' },
  { id: 'Customer Success', n: 'Customer Success', ico: '🤝' },
  { id: 'Business Analytics', n: 'Business Analytics', ico: '📈' },
  { id: 'Consulting', n: 'Consulting', ico: '🧩' },
  { id: 'Data Science', n: 'Data Science', ico: '🧠' },
  { id: 'AI & ML', n: 'AI & ML', ico: '🧬' },
  { id: 'Digital Marketing', n: 'Digital Marketing', ico: '📣' },
  { id: 'E-commerce', n: 'E-commerce', ico: '🛒' },
  { id: 'Legal & Compliance', n: 'Legal & Compliance', ico: '⚖️' },
  { id: 'Risk Management', n: 'Risk Management', ico: '🛡️' },
  { id: 'Sustainability & ESG', n: 'Sustainability & ESG', ico: '🌿' },
  { id: 'UI/UX', n: 'UI/UX', ico: '🎨' },
  { id: 'Cybersecurity', n: 'Cybersecurity', ico: '🔐' },
  { id: 'Cloud & DevOps', n: 'Cloud & DevOps', ico: '☁️' },
  { id: 'Other', n: 'Other', ico: '✨' },
  { id: 'Education & Teaching',       n: 'Education & Teaching',        ico: '🎓' },
  { id: 'Academic Research',          n: 'Academic Research',            ico: '🔬' },
  { id: 'Content & Creative Writing', n: 'Content & Creative Writing',   ico: '✍️' },
  { id: 'Journalism & Media',         n: 'Journalism & Media',           ico: '📰' },
  { id: 'Psychology & Counselling',   n: 'Psychology & Counselling',     ico: '🧠' },
  { id: 'Sociology & Social Work',    n: 'Sociology & Social Work',      ico: '🤲' },
  { id: 'Economics & Research',       n: 'Economics & Research',         ico: '📉' },
  { id: 'Fine Arts & Design',         n: 'Fine Arts & Design',           ico: '🖌️' },
  { id: 'Music & Performing Arts',    n: 'Music & Performing Arts',      ico: '🎵' },
  { id: 'Public Relations & Comms',   n: 'Public Relations & Comms',     ico: '📢' },
]

export const INDUSTRY_ROLES = {
  Finance: [
    {
      role: 'Finance Manager',
      mainRole: true,
      desc: 'Lead financial strategy, audit & P&L for an organisation',
      jobs: '14,200+',
      apnaJobs: '2,840',
      growth: '+41%',
      sal: '₹65–85k',
      accelYrs: 5,
      fastYrs: 7,
      tradYrs: 9,
      dbProfiles: 2127,
      naukri: 9800,
      linkedin: 5400,
    },
    {
      role: 'Financial Analyst',
      desc: 'Analyze company financials, forecasting and business performance',
      jobs: '11,000+',
      apnaJobs: '2,200',
      growth: '+34%',
      sal: '₹45–70k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1900,
      naukri: 7600,
      linkedin: 4200,
    },
    {
      role: 'Investment Banking Associate',
      desc: 'Support fundraising, M&A and financial strategy deals',
      jobs: '3,500+',
      apnaJobs: '520',
      growth: '+28%',
      sal: '₹90k–1.8L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 640,
      naukri: 2400,
      linkedin: 1800,
    },
    {
      role: 'FP&A Manager',
      desc: 'Lead budgeting, forecasting and strategic finance planning',
      jobs: '5,200+',
      apnaJobs: '980',
      growth: '+36%',
      sal: '₹80k–1.3L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 980,
      naukri: 3600,
      linkedin: 2600,
    },
    {
      role: 'Corporate Finance Manager',
      desc: 'Manage capital allocation, cash flow and financial strategy',
      jobs: '4,700+',
      apnaJobs: '860',
      growth: '+31%',
      sal: '₹1–1.6L',
      accelYrs: 4,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 880,
      naukri: 3200,
      linkedin: 2400,
    },
    {
      role: 'Risk Analyst',
      desc: 'Identify and mitigate financial and operational risks',
      jobs: '6,800+',
      apnaJobs: '1,240',
      growth: '+40%',
      sal: '₹50–75k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1220,
      naukri: 4600,
      linkedin: 3100,
    },
    {
      role: 'Treasury Manager',
      desc: 'Manage liquidity, investments and banking operations',
      jobs: '2,900+',
      apnaJobs: '520',
      growth: '+29%',
      sal: '₹1–1.8L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 720,
      naukri: 2100,
      linkedin: 1500,
    },
  ],
  HR: [
    {
      role: 'HR Manager',
      mainRole: true,
      desc: 'Lead talent, culture, and people strategy for an organisation',
      jobs: '12,400+',
      apnaJobs: '2,420',
      growth: '+38%',
      sal: '₹55–75k',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 1860,
      naukri: 8400,
      linkedin: 4900,
    },
    {
      role: 'HR Business Partner',
      desc: 'Strategic HR partner to business units and leadership',
      jobs: '7,800+',
      apnaJobs: '1,460',
      growth: '+45%',
      sal: '₹70–95k',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 1240,
      naukri: 5400,
      linkedin: 3600,
    },
    {
      role: 'Talent Acquisition Lead',
      desc: 'Lead hiring and recruitment strategy across teams',
      jobs: '10,200+',
      apnaJobs: '2,140',
      growth: '+42%',
      sal: '₹50–75k',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 1640,
      naukri: 7100,
      linkedin: 4400,
    },
    {
      role: 'Learning & Development Manager',
      desc: 'Build employee training and leadership development programs',
      jobs: '5,500+',
      apnaJobs: '980',
      growth: '+37%',
      sal: '₹60–90k',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 980,
      naukri: 3800,
      linkedin: 2600,
    },
    {
      role: 'Compensation & Benefits Specialist',
      desc: 'Manage salary structures, benefits and compensation strategy',
      jobs: '3,900+',
      apnaJobs: '680',
      growth: '+30%',
      sal: '₹65–95k',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 620,
      naukri: 2700,
      linkedin: 1900,
    },
    {
      role: 'Employee Relations Manager',
      desc: 'Handle employee engagement and workplace policies',
      jobs: '4,200+',
      apnaJobs: '740',
      growth: '+33%',
      sal: '₹55–80k',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 700,
      naukri: 2900,
      linkedin: 2100,
    },
  ],
  Marketing: [
    {
      role: 'Brand Manager',
      desc: 'Build brand positioning, campaigns and market presence',
      jobs: '8,700+',
      apnaJobs: '1,640',
      growth: '+44%',
      sal: '₹75k–1.2L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 8,
      dbProfiles: 1420,
      naukri: 6200,
      linkedin: 4100,
    },
    {
      role: 'Performance Marketing Manager',
      desc: 'Drive paid campaigns across Meta, Google and digital platforms',
      jobs: '14,500+',
      apnaJobs: '2,920',
      growth: '+58%',
      sal: '₹60–95k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 2280,
      naukri: 9200,
      linkedin: 5600,
    },
    {
      role: 'Product Marketing Manager',
      desc: 'Position products and drive go-to-market strategy',
      jobs: '6,400+',
      apnaJobs: '1,140',
      growth: '+49%',
      sal: '₹80k–1.4L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 980,
      naukri: 4200,
      linkedin: 3000,
    },
    {
      role: 'Growth Marketing Lead',
      desc: 'Scale user acquisition and revenue growth initiatives',
      jobs: '7,300+',
      apnaJobs: '1,420',
      growth: '+62%',
      sal: '₹70k–1.2L',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1180,
      naukri: 4800,
      linkedin: 3400,
    },
    {
      role: 'Content Marketing Manager',
      desc: 'Lead content strategy across channels and campaigns',
      jobs: '9,600+',
      apnaJobs: '1,840',
      growth: '+41%',
      sal: '₹45–75k',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1280,
      naukri: 6200,
      linkedin: 3900,
    },
    {
      role: 'Digital Marketing Manager',
      desc: 'Manage SEO, social media and digital acquisition channels',
      jobs: '18,000+',
      apnaJobs: '3,420',
      growth: '+55%',
      sal: '₹55–90k',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 2740,
      naukri: 11200,
      linkedin: 6800,
    },
  ],
  Sales: [
    {
      role: 'Sales Manager',
      desc: 'Lead sales teams and revenue targets for a region/business',
      jobs: '20,000+',
      apnaJobs: '4,200',
      growth: '+39%',
      sal: '₹65k–1L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 3200,
      naukri: 12400,
      linkedin: 7600,
    },
    {
      role: 'Enterprise Account Manager',
      desc: 'Manage strategic enterprise clients and long-term revenue',
      jobs: '7,000+',
      apnaJobs: '1,260',
      growth: '+43%',
      sal: '₹80k–1.5L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 1120,
      naukri: 4900,
      linkedin: 3300,
    },
    {
      role: 'Business Development Manager',
      desc: 'Drive partnerships, market expansion and lead generation',
      jobs: '16,500+',
      apnaJobs: '3,240',
      growth: '+47%',
      sal: '₹55–85k',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 2600,
      naukri: 10400,
      linkedin: 6200,
    },
    {
      role: 'Regional Sales Head',
      desc: 'Oversee sales strategy and operations across territories',
      jobs: '3,800+',
      apnaJobs: '640',
      growth: '+34%',
      sal: '₹1.2–2L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 10,
      dbProfiles: 520,
      naukri: 2600,
      linkedin: 1900,
    },
    {
      role: 'SaaS Sales Consultant',
      desc: 'Sell software products to businesses and enterprises',
      jobs: '8,200+',
      apnaJobs: '1,640',
      growth: '+61%',
      sal: '₹70k–1.3L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1320,
      naukri: 5800,
      linkedin: 4200,
    },
    {
      role: 'Channel Sales Manager',
      desc: 'Manage partner networks and indirect sales channels',
      jobs: '5,600+',
      apnaJobs: '1,020',
      growth: '+36%',
      sal: '₹60–95k',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 920,
      naukri: 4100,
      linkedin: 2700,
    },
  ],
  Operations: [
    {
      role: 'Operations Manager',
      desc: 'Optimize daily business operations and process efficiency',
      jobs: '15,000+',
      apnaJobs: '3,100',
      growth: '+35%',
      sal: '₹60–95k',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 2400,
      naukri: 9800,
      linkedin: 6200,
    },
    {
      role: 'Program Manager',
      desc: 'Lead cross-functional business initiatives and execution',
      jobs: '9,200+',
      apnaJobs: '1,740',
      growth: '+46%',
      sal: '₹80k–1.5L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 1480,
      naukri: 6400,
      linkedin: 4500,
    },
    {
      role: 'Process Excellence Manager',
      desc: 'Improve operational systems and business workflows',
      jobs: '4,900+',
      apnaJobs: '920',
      growth: '+33%',
      sal: '₹70k–1.1L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 820,
      naukri: 3400,
      linkedin: 2400,
    },
    {
      role: 'Supply Operations Lead',
      desc: 'Manage inventory, logistics and fulfillment operations',
      jobs: '8,100+',
      apnaJobs: '1,540',
      growth: '+40%',
      sal: '₹55–85k',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 1240,
      naukri: 5600,
      linkedin: 3900,
    },
    {
      role: 'Vendor Operations Manager',
      desc: 'Handle supplier performance and procurement operations',
      jobs: '4,400+',
      apnaJobs: '820',
      growth: '+29%',
      sal: '₹50–80k',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 740,
      naukri: 3200,
      linkedin: 2100,
    },
    {
      role: 'Logistics Manager',
      desc: 'Manage transportation, warehousing and delivery systems',
      jobs: '7,600+',
      apnaJobs: '1,420',
      growth: '+38%',
      sal: '₹60–90k',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 1100,
      naukri: 5200,
      linkedin: 3600,
    },
  ],
  Product: [
    {
      role: 'Product Manager',
      desc: 'Own product strategy, roadmap and execution',
      jobs: '12,500+',
      apnaJobs: '2,320',
      growth: '+67%',
      sal: '₹1–2L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 2100,
      naukri: 9200,
      linkedin: 6800,
    },
    {
      role: 'Associate Product Manager',
      desc: 'Support product launches, features and user experience',
      jobs: '10,400+',
      apnaJobs: '1,980',
      growth: '+72%',
      sal: '₹70k–1.2L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1880,
      naukri: 7600,
      linkedin: 5400,
    },
    {
      role: 'Growth Product Manager',
      desc: 'Drive user growth, activation and retention metrics',
      jobs: '5,800+',
      apnaJobs: '1,060',
      growth: '+69%',
      sal: '₹1–1.8L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 980,
      naukri: 4200,
      linkedin: 3200,
    },
    {
      role: 'Product Operations Manager',
      desc: 'Streamline product workflows and execution systems',
      jobs: '4,100+',
      apnaJobs: '740',
      growth: '+48%',
      sal: '₹75k–1.1L',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 720,
      naukri: 3100,
      linkedin: 2400,
    },
    {
      role: 'Technical Product Manager',
      desc: 'Manage technology-heavy products and engineering coordination',
      jobs: '6,700+',
      apnaJobs: '1,240',
      growth: '+64%',
      sal: '₹1.2–2.2L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 1180,
      naukri: 4800,
      linkedin: 3900,
    },
    {
      role: 'Product Analytics Lead',
      desc: 'Use data insights to improve product performance',
      jobs: '4,900+',
      apnaJobs: '920',
      growth: '+58%',
      sal: '₹80k–1.4L',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 940,
      naukri: 3600,
      linkedin: 2800,
    },
  ],
  IT: [
    {
      role: 'Software Development Engineer (SDE) II',
      desc: 'Design, develop, and maintain complex software systems and scalable code',
      jobs: '45,000+',
      apnaJobs: '8,400',
      growth: '+52%',
      sal: '₹1.2–2.2L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 5200,
      naukri: 32000,
      linkedin: 21000,
    },
    {
      role: 'System Administrator',
      desc: 'Manage, troubleshoot, and maintain server and network infrastructure',
      jobs: '12,400+',
      apnaJobs: '2,200',
      growth: '+22%',
      sal: '₹55–85k',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1840,
      naukri: 8600,
      linkedin: 5400,
    },
    {
      role: 'Full Stack Developer',
      desc: 'Build end-to-end web applications (Frontend + Backend)',
      jobs: '32,000+',
      apnaJobs: '6,100',
      growth: '+47%',
      sal: '₹80k–1.5L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 4400,
      naukri: 24400,
      linkedin: 16200,
    },
    {
      role: 'Database Administrator (DBA)',
      desc: 'Ensure data integrity, security, and performance of database systems',
      jobs: '8,900+',
      apnaJobs: '1,520',
      growth: '+28%',
      sal: '₹70k–1.1L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 1320,
      naukri: 6100,
      linkedin: 4200,
    },
    {
      role: 'IT Support Lead',
      desc: 'Manage technical support teams and service delivery protocols',
      jobs: '15,600+',
      apnaJobs: '2,820',
      growth: '+25%',
      sal: '₹60–90k',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 2100,
      naukri: 10400,
      linkedin: 6800,
    },
    {
      role: 'Solutions Architect',
      desc: 'Design comprehensive IT solutions that solve specific business problems',
      jobs: '7,200+',
      apnaJobs: '1,140',
      growth: '+39%',
      sal: '₹1.8–3.2L',
      accelYrs: 5,
      fastYrs: 7,
      tradYrs: 10,
      dbProfiles: 880,
      naukri: 5200,
      linkedin: 4100,
    },
  ],
  Strategy: [
    {
      role: 'Strategy Associate',
      desc: 'Conduct market sizing, competitive benchmarking, and internal audits',
      jobs: '4,200+',
      apnaJobs: '620',
      growth: '+35%',
      sal: '₹90k–1.4L',
      accelYrs: 1.5,
      fastYrs: 2.5,
      tradYrs: 4,
      dbProfiles: 780,
      naukri: 3100,
      linkedin: 2200,
    },
    {
      role: 'Corporate Strategy Manager',
      desc: 'Direct long-term growth initiatives, M&A, and business pivots',
      jobs: '3,400+',
      apnaJobs: '520',
      growth: '+31%',
      sal: '₹1.5–2.5L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 520,
      naukri: 2400,
      linkedin: 1900,
    },
    {
      role: 'Chief of Staff',
      desc: 'Strategic advisor to CEOs, managing high-priority cross-departmental projects',
      jobs: '2,100+',
      apnaJobs: '320',
      growth: '+40%',
      sal: '₹1.8–3L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 320,
      naukri: 1600,
      linkedin: 1400,
    },
    {
      role: 'Business Transformation Lead',
      desc: 'Lead large-scale organizational changes and digital shifts',
      jobs: '2,800+',
      apnaJobs: '420',
      growth: '+37%',
      sal: '₹2.2–3.8L',
      accelYrs: 5,
      fastYrs: 7,
      tradYrs: 10,
      dbProfiles: 420,
      naukri: 2100,
      linkedin: 1800,
    },
    {
      role: 'Market Entry Specialist',
      desc: 'Analyze and execute strategies for launching into new geographies',
      jobs: '1,500+',
      apnaJobs: '240',
      growth: '+29%',
      sal: '₹1.2–2L',
      accelYrs: 3,
      fastYrs: 4.5,
      tradYrs: 7,
      dbProfiles: 260,
      naukri: 1100,
      linkedin: 1000,
    },
    {
      role: 'Strategic Partnerships Manager',
      desc: 'Build alliances with other firms to drive mutual growth',
      jobs: '5,600+',
      apnaJobs: '940',
      growth: '+43%',
      sal: '₹1.1–1.9L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 980,
      naukri: 4100,
      linkedin: 3200,
    },
  ],
  SCM: [
    {
      role: 'SCM Analyst',
      desc: 'Analyze supply chain data to reduce costs and improve efficiency',
      jobs: '8,100+',
      apnaJobs: '1,520',
      growth: '+38%',
      sal: '₹50–75k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1240,
      naukri: 5600,
      linkedin: 3900,
    },
    {
      role: 'Demand Planner',
      desc: 'Predict future product demand using historical data and market trends',
      jobs: '4,800+',
      apnaJobs: '860',
      growth: '+41%',
      sal: '₹65–95k',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 820,
      naukri: 3400,
      linkedin: 2400,
    },
    {
      role: 'Warehouse Manager',
      desc: 'Oversee storage, safety, and dispatch operations within a facility',
      jobs: '10,200+',
      apnaJobs: '1,940',
      growth: '+26%',
      sal: '₹55–85k',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 1680,
      naukri: 7200,
      linkedin: 4800,
    },
    {
      role: 'Logistics & Distribution Lead',
      desc: 'Manage the physical movement of goods across transport networks',
      jobs: '6,400+',
      apnaJobs: '1,140',
      growth: '+34%',
      sal: '₹90k–1.4L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 1100,
      naukri: 4600,
      linkedin: 3200,
    },
    {
      role: 'Global Sourcing Manager',
      desc: 'Identify and negotiate with international suppliers for raw materials',
      jobs: '3,200+',
      apnaJobs: '520',
      growth: '+30%',
      sal: '₹1.3–2.2L',
      accelYrs: 5,
      fastYrs: 7,
      tradYrs: 10,
      dbProfiles: 520,
      naukri: 2300,
      linkedin: 1800,
    },
    {
      role: 'Inventory Control Specialist',
      desc: 'Minimize stockouts and overstock through rigorous monitoring',
      jobs: '9,600+',
      apnaJobs: '1,820',
      growth: '+33%',
      sal: '₹45–70k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1420,
      naukri: 6800,
      linkedin: 4200,
    },
  ],
  'Customer Success': [
    {
      role: 'Customer Success Manager (CSM)',
      desc: 'Ensure clients achieve their desired outcomes with the product',
      jobs: '11,400+',
      apnaJobs: '2,140',
      growth: '+49%',
      sal: '₹70k–1.1L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1820,
      naukri: 8200,
      linkedin: 5600,
    },
    {
      role: 'Implementation Specialist',
      desc: 'Lead the technical onboarding and setup for new clients',
      jobs: '7,200+',
      apnaJobs: '1,420',
      growth: '+36%',
      sal: '₹60–90k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1180,
      naukri: 5200,
      linkedin: 3600,
    },
    {
      role: 'Renewal Manager',
      desc: 'Focus specifically on contract renewals and preventing churn',
      jobs: '4,500+',
      apnaJobs: '820',
      growth: '+42%',
      sal: '₹80k–1.2L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 780,
      naukri: 3200,
      linkedin: 2400,
    },
    {
      role: 'Customer Advocacy Lead',
      desc: 'Turn happy customers into brand ambassadors and case studies',
      jobs: '2,300+',
      apnaJobs: '420',
      growth: '+31%',
      sal: '₹75k–1.1L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 420,
      naukri: 1600,
      linkedin: 1400,
    },
    {
      role: 'VP of Customer Success',
      desc: 'Strategic leadership of the entire post-sales customer journey',
      jobs: '900+',
      apnaJobs: '140',
      growth: '+35%',
      sal: '₹4–7L',
      accelYrs: 8,
      fastYrs: 10,
      tradYrs: 15,
      dbProfiles: 120,
      naukri: 620,
      linkedin: 520,
    },
    {
      role: 'Technical Account Manager (TAM)',
      desc: 'Provide dedicated technical advisory and support for key accounts',
      jobs: '5,100+',
      apnaJobs: '980',
      growth: '+44%',
      sal: '₹1.2–2L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 920,
      naukri: 3800,
      linkedin: 2900,
    },
  ],
  'Business Analytics': [
    {
      role: 'Business Analyst',
      desc: 'Translate business needs into technical requirements and data-driven insights',
      jobs: '22,000+',
      apnaJobs: '4,100',
      growth: '+38%',
      sal: '₹65k–1.1L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 3200,
      naukri: 15800,
      linkedin: 10400,
    },
    {
      role: 'Business Intelligence (BI) Developer',
      desc: 'Design and maintain dashboards and reporting systems using SQL, PowerBI/Tableau',
      jobs: '14,500+',
      apnaJobs: '2,820',
      growth: '+42%',
      sal: '₹75k–1.2L',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 2280,
      naukri: 10400,
      linkedin: 7200,
    },
    {
      role: 'Analytics Manager',
      desc: 'Lead a team of analysts to solve cross-departmental business problems',
      jobs: '5,800+',
      apnaJobs: '1,140',
      growth: '+34%',
      sal: '₹1.5–2.2L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 980,
      naukri: 4200,
      linkedin: 3200,
    },
    {
      role: 'Marketing Analyst',
      desc: 'Track campaign performance, ROI, and customer acquisition costs (CAC)',
      jobs: '8,200+',
      apnaJobs: '1,560',
      growth: '+31%',
      sal: '₹55–85k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1540,
      naukri: 6100,
      linkedin: 4200,
    },
    {
      role: 'Supply Chain Analyst',
      desc: 'Optimize inventory levels and logistics routes using predictive modeling',
      jobs: '6,400+',
      apnaJobs: '1,220',
      growth: '+29%',
      sal: '₹60–90k',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1180,
      naukri: 4800,
      linkedin: 3400,
    },
    {
      role: 'Quantitative Analyst (FinTech)',
      desc: 'Develop mathematical models for pricing, risk, and algorithmic trading',
      jobs: '3,100+',
      apnaJobs: '520',
      growth: '+45%',
      sal: '₹1.4–2.5L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 520,
      naukri: 2200,
      linkedin: 1900,
    },
  ],
  Consulting: [
    {
      role: 'Management Consultant',
      desc: 'Advise C-suite on organizational strategy, operations, and growth',
      jobs: '8,500+',
      apnaJobs: '1,420',
      growth: '+36%',
      sal: '₹1.5–2.4L',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1180,
      naukri: 6100,
      linkedin: 5400,
    },
    {
      role: 'Strategy Consultant',
      desc: 'Long-term planning, market entry, and competitive positioning',
      jobs: '4,200+',
      apnaJobs: '720',
      growth: '+33%',
      sal: '₹1.8–2.8L',
      accelYrs: 3,
      fastYrs: 4.5,
      tradYrs: 7,
      dbProfiles: 620,
      naukri: 3100,
      linkedin: 2800,
    },
    {
      role: 'Operations Consultant',
      desc: 'Restructure business processes and supply chains for maximum efficiency',
      jobs: '5,600+',
      apnaJobs: '980',
      growth: '+28%',
      sal: '₹1.2–1.9L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 820,
      naukri: 4100,
      linkedin: 3600,
    },
    {
      role: 'Tech Transformation Consultant',
      desc: 'Guide companies through large-scale digital and cloud migrations',
      jobs: '11,200+',
      apnaJobs: '1,840',
      growth: '+48%',
      sal: '₹1.4–2.2L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 1240,
      naukri: 8200,
      linkedin: 6800,
    },
    {
      role: 'Human Capital Consultant',
      desc: 'Advise on culture, leadership development, and workforce planning',
      jobs: '3,800+',
      apnaJobs: '620',
      growth: '+30%',
      sal: '₹90k–1.4L',
      accelYrs: 4,
      fastYrs: 5.5,
      tradYrs: 8,
      dbProfiles: 520,
      naukri: 2700,
      linkedin: 2400,
    },
    {
      role: 'Economic/Public Sector Consultant',
      desc: 'Work with governments and NGOs on policy and development projects',
      jobs: '2,100+',
      apnaJobs: '320',
      growth: '+22%',
      sal: '₹1–1.6L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 320,
      naukri: 1600,
      linkedin: 1400,
    },
  ],
  'Data Science': [
    {
      role: 'Junior Data Scientist',
      desc: 'Clean data, perform EDA, and build baseline machine learning models',
      jobs: '15,000+',
      apnaJobs: '2,820',
      growth: '+52%',
      sal: '₹80k–1.4L',
      accelYrs: 1.5,
      fastYrs: 2.5,
      tradYrs: 4,
      dbProfiles: 2100,
      naukri: 10400,
      linkedin: 6800,
    },
    {
      role: 'Data Scientist',
      desc: 'Lead end-to-end ML projects, from problem definition to deployment',
      jobs: '12,400+',
      apnaJobs: '2,240',
      growth: '+55%',
      sal: '₹1.6–2.8L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 1820,
      naukri: 8600,
      linkedin: 6200,
    },
    {
      role: 'Data Architect',
      desc: 'Design the blueprint for organizational data management and flows',
      jobs: '4,800+',
      apnaJobs: '820',
      growth: '+41%',
      sal: '₹2.2–4.5L',
      accelYrs: 5,
      fastYrs: 7,
      tradYrs: 10,
      dbProfiles: 720,
      naukri: 3400,
      linkedin: 2800,
    },
    {
      role: 'NLP Scientist',
      desc: 'Build models for language understanding, chatbots, and translation',
      jobs: '3,200+',
      apnaJobs: '520',
      growth: '+60%',
      sal: '₹1.5–2.4L',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 520,
      naukri: 2400,
      linkedin: 2100,
    },
    {
      role: 'Computer Vision Engineer',
      desc: 'Develop systems for image recognition and spatial awareness',
      jobs: '2,900+',
      apnaJobs: '420',
      growth: '+58%',
      sal: '₹1.4–2.2L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 420,
      naukri: 2100,
      linkedin: 1800,
    },
    {
      role: 'MLOps Engineer',
      desc: 'Bridge the gap between data science and production deployment/scaling',
      jobs: '5,500+',
      apnaJobs: '940',
      growth: '+65%',
      sal: '₹1.8–3L',
      accelYrs: 2.5,
      fastYrs: 3.5,
      tradYrs: 5,
      dbProfiles: 980,
      naukri: 4100,
      linkedin: 3600,
    },
  ],
  'AI & ML': [
    {
      role: 'AI Engineer',
      desc: 'Build and integrate AI capabilities (GenAI, LLMs) into products',
      jobs: '18,000+',
      apnaJobs: '3,100',
      growth: '+72%',
      sal: '₹1.5–3L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 2400,
      naukri: 12400,
      linkedin: 9200,
    },
    {
      role: 'GenAI Developer',
      desc: 'Build apps using LLMs, fine-tuning, and RAG pipelines (LangChain)',
      jobs: '9,500+',
      apnaJobs: '1,740',
      growth: '+110%',
      sal: '₹1.2–2.5L',
      accelYrs: 1.5,
      fastYrs: 2.5,
      tradYrs: 4,
      dbProfiles: 1180,
      naukri: 6400,
      linkedin: 5200,
    },
    {
      role: 'Reinforcement Learning Engineer',
      desc: 'Develop models that learn through trial and error (Robotics/Gaming)',
      jobs: '1,200+',
      apnaJobs: '180',
      growth: '+45%',
      sal: '₹2–3.5L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 180,
      naukri: 820,
      linkedin: 760,
    },
    {
      role: 'AI Product Manager',
      desc: 'Define the roadmap for AI-first products and manage data pipelines',
      jobs: '4,100+',
      apnaJobs: '720',
      growth: '+62%',
      sal: '₹1.8–3.2L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 680,
      naukri: 3100,
      linkedin: 2800,
    },
    {
      role: 'Deep Learning Specialist',
      desc: 'Design and train complex neural networks for specialized tasks',
      jobs: '5,300+',
      apnaJobs: '920',
      growth: '+54%',
      sal: '₹1.6–2.8L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 940,
      naukri: 3600,
      linkedin: 3200,
    },
    {
      role: 'AI Ethics & Compliance Officer',
      desc: 'Ensure AI systems are fair, unbiased, and compliant with laws',
      jobs: '800+',
      apnaJobs: '120',
      growth: '+40%',
      sal: '₹1.4–2L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 120,
      naukri: 520,
      linkedin: 480,
    },
  ],
  'Digital Marketing': [
    {
      role: 'SEO Specialist',
      desc: 'Drive organic traffic through technical site audits and keyword strategy',
      jobs: '15,600+',
      apnaJobs: '2,940',
      growth: '+38%',
      sal: '₹55–90k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 2280,
      naukri: 10400,
      linkedin: 6800,
    },
    {
      role: 'Performance Marketing Manager',
      desc: 'Manage paid ad spend (Google/Meta) to drive direct conversions',
      jobs: '9,200+',
      apnaJobs: '1,740',
      growth: '+55%',
      sal: '₹1–1.6L',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1480,
      naukri: 6400,
      linkedin: 4500,
    },
    {
      role: 'Social Media Strategist',
      desc: 'Build community and brand presence across social platforms',
      jobs: '12,800+',
      apnaJobs: '2,420',
      growth: '+42%',
      sal: '₹45–75k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1820,
      naukri: 8600,
      linkedin: 5200,
    },
    {
      role: 'Email Marketing Lead',
      desc: 'Design retention campaigns and automated customer journeys',
      jobs: '4,500+',
      apnaJobs: '820',
      growth: '+28%',
      sal: '₹65–95k',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 780,
      naukri: 3200,
      linkedin: 2400,
    },
    {
      role: 'Affiliate Marketing Manager',
      desc: 'Build and manage third-party networks for lead generation',
      jobs: '3,100+',
      apnaJobs: '520',
      growth: '+32%',
      sal: '₹75k–1.1L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 520,
      naukri: 2200,
      linkedin: 1800,
    },
    {
      role: 'Director of Digital Marketing',
      desc: 'Lead total digital strategy and budget for a large brand',
      jobs: '1,200+',
      apnaJobs: '180',
      growth: '+36%',
      sal: '₹3–5.5L',
      accelYrs: 7,
      fastYrs: 9,
      tradYrs: 12,
      dbProfiles: 180,
      naukri: 820,
      linkedin: 760,
    },
  ],
  'E-commerce': [
    {
      role: 'E-commerce Operations Manager',
      desc: 'Manage marketplace listings, inventory, and fulfillment (Amazon/Flipkart)',
      jobs: '18,400+',
      apnaJobs: '3,420',
      growth: '+44%',
      sal: '₹60–90k',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 2400,
      naukri: 12800,
      linkedin: 8100,
    },
    {
      role: 'Category Manager',
      desc: 'Own the P&L and growth of a specific product category (e.g., Electronics)',
      jobs: '6,500+',
      apnaJobs: '1,140',
      growth: '+47%',
      sal: '₹1.1–1.8L',
      accelYrs: 3,
      fastYrs: 4.5,
      tradYrs: 7,
      dbProfiles: 980,
      naukri: 4600,
      linkedin: 3200,
    },
    {
      role: 'D2C Brand Head',
      desc: 'Build and scale a brand selling directly through its own website',
      jobs: '2,200+',
      apnaJobs: '320',
      growth: '+58%',
      sal: '₹1.5–2.5L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 320,
      naukri: 1600,
      linkedin: 1400,
    },
    {
      role: 'Marketplace Specialist',
      desc: 'Optimize presence and ads specifically for large marketplaces',
      jobs: '11,500+',
      apnaJobs: '2,100',
      growth: '+41%',
      sal: '₹50–80k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1820,
      naukri: 8200,
      linkedin: 5600,
    },
    {
      role: 'Fulfillment/Warehouse Manager',
      desc: 'Ensure rapid delivery and low error rates in the delivery chain',
      jobs: '8,900+',
      apnaJobs: '1,520',
      growth: '+38%',
      sal: '₹70k–1.1L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 1320,
      naukri: 6100,
      linkedin: 4200,
    },
    {
      role: 'Retention Lead (E-comm)',
      desc: 'Maximize customer lifetime value (LTV) through loyalty programs',
      jobs: '3,400+',
      apnaJobs: '520',
      growth: '+45%',
      sal: '₹85k–1.3L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 520,
      naukri: 2400,
      linkedin: 2100,
    },
  ],
  'Legal & Compliance': [
    {
      role: 'Legal Associate',
      desc: 'Draft contracts, conduct legal research, and manage corporate documentation',
      jobs: '9,800+',
      apnaJobs: '1,520',
      growth: '+34%',
      sal: '₹75k–1.2L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1320,
      naukri: 6100,
      linkedin: 4200,
    },
    {
      role: 'Compliance Manager',
      desc: 'Ensure organization follows industry regulations and internal policies',
      jobs: '6,400+',
      apnaJobs: '980',
      growth: '+45%',
      sal: '₹1.1–1.8L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 980,
      naukri: 4100,
      linkedin: 3200,
    },
    {
      role: 'Company Secretary (CS)',
      desc: 'Manage board communications and ensure statutory compliance',
      jobs: '5,200+',
      apnaJobs: '820',
      growth: '+31%',
      sal: '₹90k–1.5L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 720,
      naukri: 3600,
      linkedin: 2800,
    },
    {
      role: 'Data Privacy Officer (DPO)',
      desc: 'Oversee data protection strategy and compliance with DPDP Act',
      jobs: '2,900+',
      apnaJobs: '420',
      growth: '+62%',
      sal: '₹1.5–2.5L',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 420,
      naukri: 2100,
      linkedin: 1800,
    },
    {
      role: 'Regulatory Affairs Lead',
      desc: 'Manage relationships with government bodies and handle licensing',
      jobs: '1,700+',
      apnaJobs: '240',
      growth: '+38%',
      sal: '₹1.8–3.2L',
      accelYrs: 5,
      fastYrs: 7,
      tradYrs: 10,
      dbProfiles: 240,
      naukri: 1100,
      linkedin: 1000,
    },
    {
      role: 'General Counsel',
      desc: 'Strategic legal advisor to the CEO and Board on global legal risks',
      jobs: '400+',
      apnaJobs: '60',
      growth: '+26%',
      sal: '₹4.5–8L',
      accelYrs: 8,
      fastYrs: 10,
      tradYrs: 15,
      dbProfiles: 60,
      naukri: 240,
      linkedin: 220,
    },
  ],
  'Risk Management': [
    {
      role: 'Risk Analyst',
      desc: 'Identify and quantify potential financial and operational risks',
      jobs: '7,100+',
      apnaJobs: '1,240',
      growth: '+40%',
      sal: '₹65–95k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1220,
      naukri: 4600,
      linkedin: 3100,
    },
    {
      role: 'Internal Auditor',
      desc: 'Conduct independent reviews of internal controls and risk systems',
      jobs: '11,400+',
      apnaJobs: '1,940',
      growth: '+33%',
      sal: '₹85k–1.3L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 1680,
      naukri: 7200,
      linkedin: 4800,
    },
    {
      role: 'Operational Risk Manager',
      desc: 'Mitigate risks arising from failed internal processes or people',
      jobs: '4,800+',
      apnaJobs: '820',
      growth: '+37%',
      sal: '₹1.4–2.2L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 780,
      naukri: 3400,
      linkedin: 2400,
    },
    {
      role: 'Market Risk Specialist',
      desc: 'Manage exposure to price fluctuations, interest rates, and FX',
      jobs: '3,200+',
      apnaJobs: '520',
      growth: '+35%',
      sal: '₹1.8–2.8L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 520,
      naukri: 2300,
      linkedin: 1800,
    },
    {
      role: 'Business Continuity Lead',
      desc: 'Develop recovery plans for disasters and major business disruptions',
      jobs: '1,900+',
      apnaJobs: '240',
      growth: '+32%',
      sal: '₹1.6–2.4L',
      accelYrs: 5,
      fastYrs: 7,
      tradYrs: 10,
      dbProfiles: 240,
      naukri: 1200,
      linkedin: 1000,
    },
    {
      role: 'Chief Risk Officer (CRO)',
      desc: 'Final authority on organizational risk appetite and mitigation strategy',
      jobs: '350+',
      apnaJobs: '50',
      growth: '+29%',
      sal: '₹5–10L',
      accelYrs: 9,
      fastYrs: 12,
      tradYrs: 18,
      dbProfiles: 50,
      naukri: 220,
      linkedin: 200,
    },
  ],
  'Sustainability & ESG': [
    {
      role: 'ESG Analyst',
      desc: 'Assess company performance on environmental and social metrics',
      jobs: '3,800+',
      apnaJobs: '620',
      growth: '+55%',
      sal: '₹80k–1.3L',
      accelYrs: 1.5,
      fastYrs: 2.5,
      tradYrs: 4,
      dbProfiles: 520,
      naukri: 2400,
      linkedin: 2100,
    },
    {
      role: 'Sustainability Consultant',
      desc: 'Advise firms on net-zero pathways and green reporting frameworks',
      jobs: '5,100+',
      apnaJobs: '860',
      growth: '+68%',
      sal: '₹1.1–1.9L',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 720,
      naukri: 3100,
      linkedin: 2800,
    },
    {
      role: 'Circular Economy Specialist',
      desc: 'Design waste-reduction and resource-regeneration business models',
      jobs: '1,400+',
      apnaJobs: '220',
      growth: '+42%',
      sal: '₹1.3–2.2L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 220,
      naukri: 900,
      linkedin: 820,
    },
    {
      role: 'Carbon Markets Trader',
      desc: 'Manage purchase and sale of carbon credits and offsets',
      jobs: '800+',
      apnaJobs: '120',
      growth: '+75%',
      sal: '₹1.5–2.5L',
      accelYrs: 2,
      fastYrs: 3.5,
      tradYrs: 5,
      dbProfiles: 120,
      naukri: 520,
      linkedin: 480,
    },
    {
      role: 'Head of CSR',
      desc: 'Lead social impact initiatives and community development programs',
      jobs: '2,200+',
      apnaJobs: '320',
      growth: '+24%',
      sal: '₹1.8–3L',
      accelYrs: 6,
      fastYrs: 8,
      tradYrs: 12,
      dbProfiles: 320,
      naukri: 1400,
      linkedin: 1200,
    },
    {
      role: 'ESG Reporting Lead (BRSR)',
      desc: 'Oversee compliance with SEBI’s Business Responsibility & Sustainability Reporting',
      jobs: '3,500+',
      apnaJobs: '520',
      growth: '+60%',
      sal: '₹1.4–2.3L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 520,
      naukri: 2200,
      linkedin: 1800,
    },
  ],
  'UI/UX': [
    {
      role: 'UX Researcher',
      desc: 'Conduct user studies to understand behavior, needs, and pain points',
      jobs: '6,200+',
      apnaJobs: '980',
      growth: '+44%',
      sal: '₹80k–1.5L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 720,
      naukri: 4200,
      linkedin: 3400,
    },
    {
      role: 'Product Designer (UI)',
      desc: 'Create visual interfaces, prototypes, and design systems',
      jobs: '14,500+',
      apnaJobs: '2,240',
      growth: '+48%',
      sal: '₹90k–1.8L',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1820,
      naukri: 10400,
      linkedin: 8100,
    },
    {
      role: 'Interaction Designer',
      desc: 'Design the motion and functionality of digital interactions',
      jobs: '3,900+',
      apnaJobs: '620',
      growth: '+41%',
      sal: '₹1–2.1L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 620,
      naukri: 2700,
      linkedin: 2400,
    },
    {
      role: 'Design Systems Lead',
      desc: 'Maintain consistency across products by building scalable design components',
      jobs: '1,800+',
      apnaJobs: '240',
      growth: '+52%',
      sal: '₹2.2–3.8L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 240,
      naukri: 1100,
      linkedin: 1000,
    },
    {
      role: 'UX Writer',
      desc: 'Write clear, concise microcopy for digital product interfaces',
      jobs: '2,400+',
      apnaJobs: '320',
      growth: '+38%',
      sal: '₹75k–1.3L',
      accelYrs: 2.5,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 320,
      naukri: 1600,
      linkedin: 1400,
    },
    {
      role: 'Director of Design',
      desc: 'Lead design culture, strategy, and cross-functional design teams',
      jobs: '650+',
      apnaJobs: '90',
      growth: '+33%',
      sal: '₹4–7.5L',
      accelYrs: 7,
      fastYrs: 10,
      tradYrs: 14,
      dbProfiles: 90,
      naukri: 420,
      linkedin: 380,
    },
  ],
  Cybersecurity: [
    {
      role: 'Security Analyst (L1/L2)',
      desc: 'Monitor networks for security breaches and investigate incidents',
      jobs: '18,200+',
      apnaJobs: '3,100',
      growth: '+58%',
      sal: '₹70k–1.2L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 2400,
      naukri: 12400,
      linkedin: 9200,
    },
    {
      role: 'Ethical Hacker (Pen Tester)',
      desc: 'Find and fix vulnerabilities by simulating cyberattacks',
      jobs: '5,400+',
      apnaJobs: '940',
      growth: '+55%',
      sal: '₹1.1–2L',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 980,
      naukri: 4100,
      linkedin: 3600,
    },
    {
      role: 'Security Architect',
      desc: 'Design robust security structures for organizational networks',
      jobs: '3,800+',
      apnaJobs: '620',
      growth: '+46%',
      sal: '₹2.5–4.5L',
      accelYrs: 5,
      fastYrs: 7,
      tradYrs: 10,
      dbProfiles: 520,
      naukri: 2700,
      linkedin: 2400,
    },
    {
      role: 'Incident Response Lead',
      desc: 'Direct the containment and recovery efforts after a major breach',
      jobs: '2,100+',
      apnaJobs: '320',
      growth: '+52%',
      sal: '₹1.8–3L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 320,
      naukri: 1600,
      linkedin: 1400,
    },
    {
      role: 'Application Security Engineer',
      desc: 'Secure the software development lifecycle (DevSecOps)',
      jobs: '4,500+',
      apnaJobs: '740',
      growth: '+60%',
      sal: '₹1.6–2.8L',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 7,
      dbProfiles: 720,
      naukri: 3200,
      linkedin: 2800,
    },
    {
      role: 'CISO (Chief Information Security Officer)',
      desc: 'Corporate head of information security and risk management',
      jobs: '480+',
      apnaJobs: '70',
      growth: '+44%',
      sal: '₹6–12L',
      accelYrs: 8,
      fastYrs: 11,
      tradYrs: 16,
      dbProfiles: 70,
      naukri: 320,
      linkedin: 300,
    },
  ],
  'Cloud & DevOps': [
    {
      role: 'DevOps Engineer',
      desc: 'Automate infrastructure, deployments, and CI/CD pipelines',
      jobs: '22,500+',
      apnaJobs: '4,180',
      growth: '+65%',
      sal: '₹1.2–2.5L',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 3200,
      naukri: 15800,
      linkedin: 11200,
    },
    {
      role: 'Cloud Architect (AWS/Azure/GCP)',
      desc: 'Design scalable and cost-effective cloud infrastructure solutions',
      jobs: '7,200+',
      apnaJobs: '1,140',
      growth: '+58%',
      sal: '₹2.8–5L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 980,
      naukri: 5200,
      linkedin: 4100,
    },
    {
      role: 'Site Reliability Engineer (SRE)',
      desc: 'Ensure high availability and performance of production systems',
      jobs: '5,900+',
      apnaJobs: '980',
      growth: '+62%',
      sal: '₹1.8–3.5L',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 920,
      naukri: 4200,
      linkedin: 3400,
    },
    {
      role: 'Cloud Security Engineer',
      desc: 'Implement identity management and encryption in cloud environments',
      jobs: '4,100+',
      apnaJobs: '740',
      growth: '+64%',
      sal: '₹1.6–3L',
      accelYrs: 3,
      fastYrs: 4.5,
      tradYrs: 7,
      dbProfiles: 720,
      naukri: 3100,
      linkedin: 2800,
    },
    {
      role: 'Platform Engineer',
      desc: 'Build internal tools to simplify the cloud for development teams',
      jobs: '3,200+',
      apnaJobs: '520',
      growth: '+55%',
      sal: '₹2.2–4L',
      accelYrs: 3.5,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 520,
      naukri: 2300,
      linkedin: 1800,
    },
    {
      role: 'Cloud Cost (FinOps) Analyst',
      desc: 'Optimize cloud spending and improve ROI on infrastructure',
      jobs: '1,200+',
      apnaJobs: '180',
      growth: '+72%',
      sal: '₹1.1–1.8L',
      accelYrs: 2.5,
      fastYrs: 3.5,
      tradYrs: 5,
      dbProfiles: 180,
      naukri: 820,
      linkedin: 760,
    },
  ],
  'Education & Teaching': [
    {
      role: 'Teaching Assistant',
      desc: 'Support senior teachers with lesson delivery, grading and student engagement in K-12 or college settings',
      jobs: '28,000+',
      apnaJobs: '7,400',
      growth: '+24%',
      sal: '₹18k–₹35k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 1,
      dbProfiles: 9600,
      naukri: 46400,
      linkedin: 16800,
    },
    {
      role: 'Online Tutor / EdTech Faculty',
      mainRole: true,
      desc: 'Deliver live and recorded subject-matter sessions on EdTech platforms to K-12 and competitive-exam students',
      jobs: '32,000+',
      apnaJobs: '8,500',
      growth: '+52%',
      sal: '₹25k–₹60k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 1,
      dbProfiles: 10900,
      naukri: 52800,
      linkedin: 19200,
    },
    {
      role: 'Curriculum Designer',
      mainRole: true,
      desc: 'Design learning outcomes, course structures and instructional content for formal education or online programs',
      jobs: '7,200+',
      apnaJobs: '1,920',
      growth: '+42%',
      sal: '₹45k–₹85k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 4,
      dbProfiles: 2480,
      naukri: 12800,
      linkedin: 5200,
    },
    {
      role: 'Corporate Trainer',
      desc: 'Design and deliver soft-skill, leadership and domain training programs for corporate clients',
      jobs: '9,800+',
      apnaJobs: '2,600',
      growth: '+36%',
      sal: '₹55k–115k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 3400,
      naukri: 17200,
      linkedin: 6800,
    },
    {
      role: 'Principal (School)',
      desc: 'Lead academic institution operations, manage faculty and drive student performance and institutional outcomes',
      jobs: '8,200+',
      apnaJobs: '2,180',
      growth: '+19%',
      sal: '₹90k–2L',
      accelYrs: 6,
      fastYrs: 9,
      tradYrs: 13,
      dbProfiles: 2820,
      naukri: 14400,
      linkedin: 5600,
    },
    {
      role: 'School Director / CEO (Education)',
      desc: 'Run a school or education group as a business, managing P&L, brand, expansion and regulatory compliance',
      jobs: '380+',
      apnaJobs: '101',
      growth: '+22%',
      sal: '₹350k–8L',
      accelYrs: 9,
      fastYrs: 13,
      tradYrs: 18,
      dbProfiles: 131,
      naukri: 656,
      linkedin: 480,
    },
  ],
  'Academic Research': [
    {
      role: 'Research Assistant',
      desc: 'Support faculty-led research projects through data collection, literature review and lab assistance',
      jobs: '12,000+',
      apnaJobs: '3,200',
      growth: '+28%',
      sal: '₹18k–₹35k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 1,
      dbProfiles: 4100,
      naukri: 20800,
      linkedin: 8200,
    },
    {
      role: 'Junior Research Analyst (Think Tank)',
      mainRole: true,
      desc: 'Produce policy briefs, data analyses and research reports for think tanks or policy organisations',
      jobs: '4,800+',
      apnaJobs: '1,280',
      growth: '+34%',
      sal: '₹35k–₹70k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 2,
      dbProfiles: 1660,
      naukri: 8600,
      linkedin: 3800,
    },
    {
      role: 'Post-Doctoral Researcher',
      mainRole: true,
      desc: 'Lead independent research projects post-PhD; publish in peer-reviewed journals and apply for research grants',
      jobs: '4,200+',
      apnaJobs: '1,120',
      growth: '+30%',
      sal: '₹50k–100k',
      accelYrs: 4,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 1440,
      naukri: 7400,
      linkedin: 3200,
    },
    {
      role: 'Assistant Professor',
      desc: 'Teach undergraduate/postgraduate courses, conduct original research and publish in indexed journals',
      jobs: '22,000+',
      apnaJobs: '5,800',
      growth: '+25%',
      sal: '₹55k–120k',
      accelYrs: 4,
      fastYrs: 5,
      tradYrs: 7,
      dbProfiles: 7600,
      naukri: 36400,
      linkedin: 14800,
    },
    {
      role: 'Principal Investigator (PI)',
      desc: 'Lead grant-funded research projects; manage lab team, budgets and external collaborations',
      jobs: '3,200+',
      apnaJobs: '860',
      growth: '+27%',
      sal: '₹120k–2.5L',
      accelYrs: 8,
      fastYrs: 10,
      tradYrs: 14,
      dbProfiles: 1100,
      naukri: 5600,
      linkedin: 2800,
    },
    {
      role: 'Chief Scientist / Principal Scientist',
      desc: 'Highest scientific authority in an organisation; direct multi-year research strategy and represent the org externally',
      jobs: '480+',
      apnaJobs: '128',
      growth: '+21%',
      sal: '₹350k–7L',
      accelYrs: 12,
      fastYrs: 15,
      tradYrs: 20,
      dbProfiles: 165,
      naukri: 828,
      linkedin: 608,
    },
  ],
  'Content & Creative Writing': [
    {
      role: 'Junior Content Writer',
      desc: 'Write blogs, articles and marketing copy under editorial guidance with a focus on SEO and accuracy',
      jobs: '18,000+',
      apnaJobs: '4,800',
      growth: '+46%',
      sal: '₹20k–₹40k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 1,
      dbProfiles: 6200,
      naukri: 30400,
      linkedin: 12000,
    },
    {
      role: 'Technical Writer',
      mainRole: true,
      desc: 'Create user manuals, API documentation and developer guides for software products',
      jobs: '7,200+',
      apnaJobs: '1,920',
      growth: '+44%',
      sal: '₹50k–100k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 3,
      dbProfiles: 2480,
      naukri: 12800,
      linkedin: 5400,
    },
    {
      role: 'Senior Content Writer',
      desc: 'Own high-impact content verticals, guide junior writers and drive SEO-driven organic growth',
      jobs: '11,000+',
      apnaJobs: '2,930',
      growth: '+44%',
      sal: '₹55k–110k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 4,
      dbProfiles: 3790,
      naukri: 19200,
      linkedin: 7600,
    },
    {
      role: 'Content Marketing Manager',
      desc: 'Lead content strategy, manage editorial calendar and drive organic demand through storytelling',
      jobs: '9,800+',
      apnaJobs: '2,600',
      growth: '+48%',
      sal: '₹100k–190k',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 3400,
      naukri: 17200,
      linkedin: 7000,
    },
    {
      role: 'Editor-in-Chief / Chief Content Officer',
      desc: 'Highest editorial authority; define publication identity, standards and multi-platform content vision',
      jobs: '680+',
      apnaJobs: '181',
      growth: '+24%',
      sal: '₹300k–6.5L',
      accelYrs: 8,
      fastYrs: 11,
      tradYrs: 15,
      dbProfiles: 234,
      naukri: 1178,
      linkedin: 840,
    },
  ],
  'Journalism & Media': [
    {
      role: 'Junior Reporter',
      desc: 'Cover assigned beats, conduct basic interviews and file news stories for print, digital or broadcast',
      jobs: '12,000+',
      apnaJobs: '3,200',
      growth: '+28%',
      sal: '₹18k–₹40k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 1,
      dbProfiles: 4100,
      naukri: 20800,
      linkedin: 8200,
    },
    {
      role: 'Sub-Editor / Copy Editor',
      mainRole: true,
      desc: 'Edit incoming copy for accuracy, style and grammar; write headlines and manage publication workflows',
      jobs: '6,400+',
      apnaJobs: '1,700',
      growth: '+24%',
      sal: '₹25k–₹55k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 2,
      dbProfiles: 2200,
      naukri: 11200,
      linkedin: 4800,
    },
    {
      role: 'News Anchor / TV Presenter',
      mainRole: true,
      desc: 'Present live news bulletins, conduct on-air interviews and host panel discussions for broadcast media',
      jobs: '2,400+',
      apnaJobs: '640',
      growth: '+30%',
      sal: '₹50k–150k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 4,
      dbProfiles: 820,
      naukri: 4200,
      linkedin: 2200,
    },
    {
      role: 'Senior Reporter / Senior Correspondent',
      desc: 'Lead high-impact beat coverage, develop exclusive investigations and build a senior source network',
      jobs: '4,800+',
      apnaJobs: '1,280',
      growth: '+25%',
      sal: '₹60k–130k',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1660,
      naukri: 8600,
      linkedin: 4000,
    },
    {
      role: 'Bureau Chief',
      desc: 'Lead a regional or international news bureau; manage reporters, develop stories and represent the outlet',
      jobs: '1,200+',
      apnaJobs: '320',
      growth: '+20%',
      sal: '₹120k–2.5L',
      accelYrs: 6,
      fastYrs: 8,
      tradYrs: 12,
      dbProfiles: 420,
      naukri: 2100,
      linkedin: 1100,
    },
    {
      role: 'Media Director / VP (Media)',
      desc: 'Lead business strategy, distribution and monetisation for a media brand or digital media company',
      jobs: '480+',
      apnaJobs: '128',
      growth: '+28%',
      sal: '₹350k–7.5L',
      accelYrs: 9,
      fastYrs: 12,
      tradYrs: 16,
      dbProfiles: 165,
      naukri: 828,
      linkedin: 608,
    },
  ],
  'Psychology & Counselling': [
    {
      role: 'Academic Counsellor',
      desc: 'Guide students on course selection, learning challenges and academic performance through one-on-one sessions',
      jobs: '14,000+',
      apnaJobs: '3,700',
      growth: '+48%',
      sal: '₹22k–₹45k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 1,
      dbProfiles: 4800,
      naukri: 24400,
      linkedin: 9600,
    },
    {
      role: 'Counselling Psychologist (Junior)',
      mainRole: true,
      desc: 'Deliver talk therapy using CBT and person-centred approaches under supervision in clinical or community settings',
      jobs: '6,400+',
      apnaJobs: '1,700',
      growth: '+46%',
      sal: '₹30k–₹60k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 3,
      dbProfiles: 2200,
      naukri: 11200,
      linkedin: 4800,
    },
    {
      role: 'HR / Corporate Wellness Counsellor',
      mainRole: true,
      desc: 'Deliver EAP services, manage employee mental health programs and conduct well-being workshops for corporates',
      jobs: '5,200+',
      apnaJobs: '1,380',
      growth: '+56%',
      sal: '₹45k–₹90k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 4,
      dbProfiles: 1780,
      naukri: 9200,
      linkedin: 4000,
    },
    {
      role: 'Clinical Psychologist',
      desc: 'Conduct psychodiagnostic assessments, formulate cases and deliver evidence-based therapy in clinical settings',
      jobs: '4,800+',
      apnaJobs: '1,280',
      growth: '+48%',
      sal: '₹55k–120k',
      accelYrs: 3,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1660,
      naukri: 8600,
      linkedin: 4000,
    },
    {
      role: 'Rehabilitation Counsellor',
      desc: 'Support individuals with disabilities in career planning, skill building and social reintegration',
      jobs: '3,600+',
      apnaJobs: '960',
      growth: '+36%',
      sal: '₹40k–₹85k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1240,
      naukri: 6400,
      linkedin: 2900,
    },
    {
      role: 'Chief Wellness Officer / VP People Experience',
      desc: 'Executive leader for employee mental health, wellness culture and psychological safety across the organisation',
      jobs: '280+',
      apnaJobs: '75',
      growth: '+54%',
      sal: '₹300k–6.5L',
      accelYrs: 8,
      fastYrs: 10,
      tradYrs: 14,
      dbProfiles: 96,
      naukri: 482,
      linkedin: 360,
    },
  ],
  'Sociology & Social Work': [
    {
      role: 'Community Outreach Worker',
      desc: 'Engage communities at the grassroots level, mobilise participation in welfare programs and collect field data',
      jobs: '18,000+',
      apnaJobs: '4,800',
      growth: '+28%',
      sal: '₹15k–₹32k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 1,
      dbProfiles: 6200,
      naukri: 30400,
      linkedin: 11200,
    },
    {
      role: 'Programme Coordinator (NGO)',
      mainRole: true,
      desc: 'Coordinate day-to-day NGO program operations, track deliverables and liaise with funders and partners',
      jobs: '12,000+',
      apnaJobs: '3,200',
      growth: '+34%',
      sal: '₹28k–₹55k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 2,
      dbProfiles: 4100,
      naukri: 20800,
      linkedin: 8200,
    },
    {
      role: 'Social Research Analyst',
      mainRole: true,
      desc: 'Conduct surveys, interviews and focus groups to generate evidence for social policy and programme design',
      jobs: '6,400+',
      apnaJobs: '1,700',
      growth: '+38%',
      sal: '₹38k–₹75k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 3,
      dbProfiles: 2200,
      naukri: 11200,
      linkedin: 4800,
    },
    {
      role: 'Policy Analyst (Social Sector)',
      desc: 'Research and analyse social welfare policies; produce briefs and recommendations for government and civil society',
      jobs: '3,600+',
      apnaJobs: '960',
      growth: '+36%',
      sal: '₹55k–115k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1240,
      naukri: 6400,
      linkedin: 2900,
    },
    {
      role: 'Social Impact Manager',
      desc: 'Measure, track and communicate the social return on investment of programs for impact investors and foundations',
      jobs: '3,200+',
      apnaJobs: '855',
      growth: '+48%',
      sal: '₹90k–190k',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 1100,
      naukri: 5600,
      linkedin: 2800,
    },
    {
      role: 'CEO / Executive Director (Development Sector)',
      desc: 'Lead a development organisation; drive strategy, fundraising, stakeholder relationships and programmatic outcomes at sca',
      jobs: '320+',
      apnaJobs: '85',
      growth: '+22%',
      sal: '₹300k–7L',
      accelYrs: 10,
      fastYrs: 13,
      tradYrs: 18,
      dbProfiles: 110,
      naukri: 553,
      linkedin: 420,
    },
  ],
  'Economics & Research': [
    {
      role: 'Junior Research Analyst',
      desc: 'Compile economic data, prepare literature reviews and support senior researchers with modelling tasks',
      jobs: '7,200+',
      apnaJobs: '1,920',
      growth: '+36%',
      sal: '₹35k–₹70k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 2,
      dbProfiles: 2480,
      naukri: 12800,
      linkedin: 5400,
    },
    {
      role: 'Economic Analyst / Junior Economist',
      mainRole: true,
      desc: 'Analyse macroeconomic indicators, prepare sector reports and support policy or business decision-making',
      jobs: '5,600+',
      apnaJobs: '1,480',
      growth: '+34%',
      sal: '₹55k–110k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 4,
      dbProfiles: 1920,
      naukri: 9800,
      linkedin: 4200,
    },
    {
      role: 'Policy Analyst / Policy Researcher',
      desc: 'Evaluate government policies for economic impact; draft white papers, briefs and budget analyses',
      jobs: '4,200+',
      apnaJobs: '1,120',
      growth: '+38%',
      sal: '₹55k–115k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 4,
      dbProfiles: 1440,
      naukri: 7400,
      linkedin: 3400,
    },
    {
      role: 'Macroeconomic Researcher / Economist',
      desc: 'Model macroeconomic scenarios, track monetary and fiscal indicators and publish economic outlook reports',
      jobs: '2,400+',
      apnaJobs: '640',
      growth: '+32%',
      sal: '₹120k–2.5L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 820,
      naukri: 4200,
      linkedin: 2200,
    },
    {
      role: 'Senior Market Research Manager',
      desc: 'Direct primary and secondary research projects; synthesise competitive intelligence and present strategic implications',
      jobs: '2,800+',
      apnaJobs: '750',
      growth: '+33%',
      sal: '₹150k–3L',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 9,
      dbProfiles: 960,
      naukri: 4800,
      linkedin: 2600,
    },
    {
      role: 'Economic Advisor / Independent Economist',
      desc: 'Provide bespoke economic advisory to government bodies, investors or businesses as an independent practitioner',
      jobs: '240+',
      apnaJobs: '64',
      growth: '+28%',
      sal: '₹350k–10L',
      accelYrs: 11,
      fastYrs: 14,
      tradYrs: 18,
      dbProfiles: 83,
      naukri: 414,
      linkedin: 320,
    },
  ],
  'Fine Arts & Design': [
    {
      role: 'Junior Graphic Designer',
      desc: 'Create visual assets — social media graphics, banners and marketing collateral — under senior designer guidance',
      jobs: '14,000+',
      apnaJobs: '3,700',
      growth: '+42%',
      sal: '₹22k–₹45k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 1,
      dbProfiles: 4800,
      naukri: 24400,
      linkedin: 9600,
    },
    {
      role: 'Motion Designer / Animator',
      mainRole: true,
      desc: 'Design animated videos, motion graphics and 2D/3D animations for digital media and branded content',
      jobs: '7,200+',
      apnaJobs: '1,920',
      growth: '+56%',
      sal: '₹45k–₹95k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 3,
      dbProfiles: 2480,
      naukri: 12800,
      linkedin: 5400,
    },
    {
      role: 'UI / UX Designer',
      desc: 'Design digital product interfaces and user experiences for web and mobile applications',
      jobs: '12,000+',
      apnaJobs: '3,200',
      growth: '+54%',
      sal: '₹70k–155k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 4,
      dbProfiles: 4100,
      naukri: 20800,
      linkedin: 8400,
    },
    {
      role: 'Design Manager',
      desc: 'Manage a team of designers, set OKRs, run hiring and foster design culture across the product organisation',
      jobs: '2,200+',
      apnaJobs: '590',
      growth: '+42%',
      sal: '₹200k–3.8L',
      accelYrs: 4,
      fastYrs: 7,
      tradYrs: 10,
      dbProfiles: 760,
      naukri: 3800,
      linkedin: 2000,
    },
    {
      role: 'Chief Design Officer (CDO)',
      desc: 'C-suite leader defining experience identity, design-led innovation and design culture company-wide',
      jobs: '160+',
      apnaJobs: '43',
      growth: '+28%',
      sal: '₹600k–14L',
      accelYrs: 9,
      fastYrs: 12,
      tradYrs: 16,
      dbProfiles: 55,
      naukri: 276,
      linkedin: 220,
    },
  ],
  'Music & Performing Arts': [
    {
      role: 'Music / Performing Arts Teacher',
      desc: 'Teach instrumental music, vocal training or performing arts to students in schools or private studios',
      jobs: '12,000+',
      apnaJobs: '3,200',
      growth: '+28%',
      sal: '₹18k–₹40k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 1,
      dbProfiles: 4100,
      naukri: 20800,
      linkedin: 7600,
    },
    {
      role: 'Dancer / Choreographer (Junior)',
      mainRole: true,
      desc: 'Perform in shows, music videos and events; assist choreographers in teaching dance routines',
      jobs: '5,200+',
      apnaJobs: '1,380',
      growth: '+34%',
      sal: '₹20k–₹60k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 2,
      dbProfiles: 1780,
      naukri: 9200,
      linkedin: 4000,
    },
    {
      role: 'Acting / Drama Coach',
      mainRole: true,
      desc: 'Train aspiring actors in voice, movement and character development through group classes and individual coaching',
      jobs: '2,400+',
      apnaJobs: '640',
      growth: '+40%',
      sal: '₹45k–100k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 820,
      naukri: 4200,
      linkedin: 2200,
    },
    {
      role: 'Choreographer',
      desc: 'Create original dance and movement sequences for films, stage shows, music videos and live events',
      jobs: '1,800+',
      apnaJobs: '480',
      growth: '+36%',
      sal: '₹60k–2L',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 620,
      naukri: 3100,
      linkedin: 1800,
    },
    {
      role: 'Performing Arts Programme Manager',
      desc: 'Run performing arts schools, festivals or corporate entertainment programs; manage artists, venues and budgets',
      jobs: '1,600+',
      apnaJobs: '425',
      growth: '+32%',
      sal: '₹80k–180k',
      accelYrs: 4,
      fastYrs: 6,
      tradYrs: 8,
      dbProfiles: 550,
      naukri: 2780,
      linkedin: 1540,
    },
    {
      role: 'Creative Producer / Artistic Director',
      desc: 'Lead creative vision for large-scale productions, entertainment companies or cultural institutions',
      jobs: '180+',
      apnaJobs: '48',
      growth: '+34%',
      sal: '₹250k–8L',
      accelYrs: 10,
      fastYrs: 13,
      tradYrs: 17,
      dbProfiles: 62,
      naukri: 310,
      linkedin: 252,
    },
  ],
  'Public Relations & Comms': [
    {
      role: 'PR Executive / Communications Executive',
      desc: 'Draft press releases, manage media lists and coordinate PR logistics for campaigns and launches',
      jobs: '9,800+',
      apnaJobs: '2,600',
      growth: '+34%',
      sal: '₹22k–₹45k',
      accelYrs: 1,
      fastYrs: 1,
      tradYrs: 1,
      dbProfiles: 3400,
      naukri: 17200,
      linkedin: 7000,
    },
    {
      role: 'PR Manager',
      mainRole: true,
      desc: 'Lead media relations, pitch stories to journalists, manage agency relationships and own brand reputation',
      jobs: '6,400+',
      apnaJobs: '1,700',
      growth: '+32%',
      sal: '₹60k–120k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 2200,
      naukri: 11200,
      linkedin: 4800,
    },
    {
      role: 'Corporate Communications Manager',
      desc: 'Manage internal and external communications, CEO messaging and corporate narrative for large organisations',
      jobs: '5,200+',
      apnaJobs: '1,380',
      growth: '+30%',
      sal: '₹80k–155k',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1780,
      naukri: 9200,
      linkedin: 4000,
    },
    {
      role: 'Public Affairs Manager',
      desc: 'Manage government relations, regulatory communications and advocacy programs for corporates or industry bodies',
      jobs: '2,400+',
      apnaJobs: '640',
      growth: '+40%',
      sal: '₹140k–2.8L',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 820,
      naukri: 4200,
      linkedin: 2200,
    },
    {
      role: 'Head of PR / Head of Communications',
      desc: 'Own the entire communications function; define narrative strategy and manage all external and internal messaging',
      jobs: '1,400+',
      apnaJobs: '373',
      growth: '+28%',
      sal: '₹250k–5L',
      accelYrs: 5,
      fastYrs: 8,
      tradYrs: 12,
      dbProfiles: 482,
      naukri: 2420,
      linkedin: 1540,
    },
    {
      role: 'Corporate Affairs Director',
      desc: 'Lead government relations, public affairs and corporate communications strategy for large enterprises or regulated indus',
      jobs: '340+',
      apnaJobs: '91',
      growth: '+30%',
      sal: '₹450k–9.5L',
      accelYrs: 9,
      fastYrs: 12,
      tradYrs: 16,
      dbProfiles: 117,
      naukri: 588,
      linkedin: 440,
    },
  ],
  Other: [
    {
      role: 'AI Prompt Engineer',
      desc: 'Design and refine prompts to get the best output from Generative AI tools for marketing, code, or research',
      jobs: '8,500+',
      apnaJobs: '1,560',
      growth: '+110%',
      sal: '₹80k–1.5L',
      accelYrs: 1,
      fastYrs: 1.5,
      tradYrs: 3,
      dbProfiles: 980,
      naukri: 6100,
      linkedin: 5200,
    },
    {
      role: 'No-Code / Low-Code Developer',
      desc: 'Build business apps and automations using Zapier, Bubble, or Webflow without traditional coding',
      jobs: '12,000+',
      apnaJobs: '2,140',
      growth: '+55%',
      sal: '₹50–90k',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: 4,
      dbProfiles: 1240,
      naukri: 8200,
      linkedin: 5400,
    },
    {
      role: 'Instructional Designer (EdTech)',
      desc: 'Create engaging online courses and corporate training modules using storytelling and learning psychology',
      jobs: '5,400+',
      apnaJobs: '980',
      growth: '+38%',
      sal: '₹60–95k',
      accelYrs: 2,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 820,
      naukri: 4100,
      linkedin: 3200,
    },
    {
      role: 'Instructional Video / Short-Form Editor',
      desc: 'Edit high-impact Reels, Shorts, and training videos for brands and the creator economy',
      jobs: '14,000+',
      apnaJobs: '2,540',
      growth: '+47%',
      sal: '₹45–80k',
      accelYrs: 1.5,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 1480,
      naukri: 9200,
      linkedin: 6800,
    },
    {
      role: 'Virtual Operations Manager',
      desc: 'Coordinate remote teams, managing schedules, digital tools, and remote workplace culture',
      jobs: '7,800+',
      apnaJobs: '1,420',
      growth: '+32%',
      sal: '₹55–85k',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 980,
      naukri: 5200,
      linkedin: 4100,
    },
    {
      role: 'Sustainable Travel & Hospitality Lead',
      desc: 'Manage eco-friendly tourism operations and sustainable guest experiences',
      jobs: '4,200+',
      apnaJobs: '740',
      growth: '+29%',
      sal: '₹50–75k',
      accelYrs: 3,
      fastYrs: 5,
      tradYrs: 8,
      dbProfiles: 620,
      naukri: 2900,
      linkedin: 2400,
    },
    {
      role: 'Wellness & Mental Health Coach (Corporate)',
      desc: 'Implement employee well-being programs and provide stress management support within organizations',
      jobs: '3,500+',
      apnaJobs: '620',
      growth: '+41%',
      sal: '₹60k–1L',
      accelYrs: 3,
      fastYrs: 4.5,
      tradYrs: 7,
      dbProfiles: 520,
      naukri: 2400,
      linkedin: 2100,
    },
    {
      role: 'Community Manager (Web3/SaaS)',
      desc: 'Build and moderate online communities (Discord, Slack, LinkedIn) to drive brand loyalty and engagement',
      jobs: '6,100+',
      apnaJobs: '1,060',
      growth: '+43%',
      sal: '₹45–70k',
      accelYrs: 2,
      fastYrs: 3,
      tradYrs: 5,
      dbProfiles: 820,
      naukri: 4200,
      linkedin: 3600,
    },
    {
      role: 'Content Strategist / Micro-Influencer Manager',
      desc: 'Manage narrative for brands and collaborations with niche creators',
      jobs: '9,200+',
      apnaJobs: '1,740',
      growth: '+36%',
      sal: '₹70k–1.1L',
      accelYrs: 2.5,
      fastYrs: 4,
      tradYrs: 6,
      dbProfiles: 1180,
      naukri: 6200,
      linkedin: 5200,
    },
    {
      role: 'Digital Product Seller / Curator',
      desc: 'Create and sell digital templates, ebooks, or curated resource kits for niches',
      jobs: '1,500,000+',
      apnaJobs: '—',
      growth: '+50%',
      sal: '₹40k–2L',
      accelYrs: 1,
      fastYrs: 2,
      tradYrs: '—',
      dbProfiles: 0,
      naukri: 0,
      linkedin: 0,
    },
  ],
}

export const COMPANY_TIERS = {
  Finance: {
    dream: ['Goldman Sachs', 'JP Morgan', 'HDFC Bank', 'Bain', 'Morgan Stanley'],
    regular: ['Deloitte', 'EY', 'KPMG', 'Axis Bank', 'ICICI Bank'],
    safe: ['BDO', 'RSM', 'Local CA Firm', 'SME Finance', 'Co-op Bank'],
  },
  HR: {
    dream: ['Microsoft', 'Unilever', 'TCS', 'Infosys', 'HUL'],
    regular: ['Wipro', 'Cognizant', 'Capgemini', 'Genpact', 'Tech Mahindra'],
    safe: ['Local SME', 'Regional Hospital', 'Education NGO', 'Manpower Agency', 'Local Retail'],
  },
  Marketing: {
    dream: ['Unilever', 'PepsiCo', 'Google', 'Meta', 'Amazon'],
    regular: ['Zomato', 'Swiggy', 'MakeMyTrip', 'Paytm', "BYJU'S"],
    safe: ['Local Agency', 'Regional Brand', 'D2C Startup', 'SME Marketer', 'Educational Portal'],
  },
  Sales: {
    dream: ['Salesforce', 'Oracle', 'HDFC Life', 'Bajaj Allianz', 'HUL'],
    regular: ['ICICI Pru', 'Tata AIA', 'SBI Life', 'Axis Direct', 'Reliance Retail'],
    safe: ['Local Distributor', 'Regional Dealer', 'SME Sales', 'Small Insurance', 'D2C Startup'],
  },
  Operations: {
    dream: ['Amazon', 'Flipkart', 'Maersk', 'DHL', 'Unilever'],
    regular: ['Delhivery', 'Blue Dart', 'Reliance', 'Tata', 'L&T'],
    safe: ['Local Logistics', 'Regional Warehouse', 'SME Ops', 'Retail Chain', 'Factory Ops'],
  },
  Product: {
    dream: ['Google', 'Microsoft', 'Amazon', 'Meta', 'Apple'],
    regular: ['Razorpay', 'PhonePe', 'Swiggy', 'Zomato', 'Freshworks'],
    safe: ['Seed Startup', 'SME SaaS', 'Agency Product', 'Services-to-Product', 'D2C Startup'],
  },
}

export const SAFE_ROLES = {
  Finance: [
    {
      role: 'Accounts Executive',
      desc: 'Stable role with steady demand across firms — strong T&E and AR/AP foundation',
      sal: '₹25–40k',
      jobs: '34,000+ openings',
      apnaJobs: '8,200',
      industry: 'Finance',
    },
    {
      role: 'Junior Auditor',
      desc: 'Entry-level audit support with structured progression and CA firm exposure',
      sal: '₹22–35k',
      jobs: '8,400+ openings',
      apnaJobs: '2,100',
      industry: 'Finance',
    },
    {
      role: 'Tax Preparation Specialist',
      desc: 'Year-round work with seasonal demand spikes — predictable career arc',
      sal: '₹20–32k',
      jobs: '12,000+ openings',
      apnaJobs: '3,400',
      industry: 'Finance',
    },
  ],
  HR: [
    {
      role: 'HR Coordinator',
      desc: 'Bread-and-butter HR ops role — universally needed across industries',
      sal: '₹22–35k',
      jobs: '18,000+ openings',
      apnaJobs: '5,100',
      industry: 'HR',
    },
    {
      role: 'Payroll Executive',
      desc: 'Specialised, high-demand role — every company with 50+ employees needs one',
      sal: '₹25–38k',
      jobs: '9,200+ openings',
      apnaJobs: '2,400',
      industry: 'HR',
    },
    {
      role: 'Recruitment Executive',
      desc: 'Always-on demand · agency or in-house · clear progression to Lead',
      sal: '₹20–32k',
      jobs: '14,000+ openings',
      apnaJobs: '4,300',
      industry: 'HR',
    },
  ],
}

export const ROLE_TAGS = {
  Finance: { chip: 't2', ico: '📊' },
  HR: { chip: 't3', ico: '👥' },
  Marketing: { chip: 'mkt', ico: '📱' },
  Sales: { chip: 'sales', ico: '💼' },
  Operations: { chip: 'biz', ico: '⚙️' },
  IT: { chip: 'tech', ico: '💻' },
  Product: { chip: 'prod', ico: '🎯' },
  Strategy: { chip: 'biz', ico: '🔍' },
  SCM: { chip: 'scm', ico: '🔗' },
  'Customer Success': { chip: 't3', ico: '🤝' },
  'Business Analytics': { chip: 'biz', ico: '📈' },
  Consulting: { chip: 'biz', ico: '🧩' },
  'Data Science': { chip: 'tech', ico: '🧠' },
  'AI & ML': { chip: 'tech', ico: '🧬' },
  'Digital Marketing': { chip: 'mkt', ico: '📣' },
  'E-commerce': { chip: 'biz', ico: '🛒' },
  'Legal & Compliance': { chip: 'biz', ico: '⚖️' },
  'Risk Management': { chip: 'biz', ico: '🛡️' },
  'Sustainability & ESG': { chip: 'biz', ico: '🌿' },
  'UI/UX': { chip: 'prod', ico: '🎨' },
  Cybersecurity: { chip: 'tech', ico: '🔐' },
  'Cloud & DevOps': { chip: 'tech', ico: '☁️' },
  'Education & Teaching': { chip: 'on', ico: '🎓' },
  'Academic Research': { chip: 'on', ico: '🔬' },
  'Content & Creative Writing': { chip: 'mkt', ico: '✍️' },
  'Journalism & Media': { chip: 'mkt', ico: '📰' },
  'Psychology & Counselling': { chip: 't3', ico: '🧠' },
  'Sociology & Social Work': { chip: 't3', ico: '🤲' },
  'Economics & Research': { chip: 'biz', ico: '📉' },
  'Fine Arts & Design': { chip: 'prod', ico: '🖌️' },
  'Music & Performing Arts': { chip: 'on', ico: '🎵' },
  'Public Relations & Comms': { chip: 'mkt', ico: '📢' },
  Other: { chip: 'on', ico: '✨' },
}

/**
 * Deep-clone a single catalogue card by industry + exact role title (Frame 2 curated packs).
 * @param {string} industry
 * @param {string} roleTitle
 * @returns {Record<string, any> | null}
 */
export function cloneRoleCard(industry, roleTitle) {
  const rows = INDUSTRY_ROLES[industry]
  if (!rows) return null
  const row = rows.find((r) => r.role === roleTitle)
  return row ? { ...row, industry } : null
}

export function flattenIndustryRoles(selIndustry = 'all') {
  const cards = []
  if (selIndustry === 'all') {
    Object.keys(INDUSTRY_ROLES).forEach((ind) => {
      INDUSTRY_ROLES[ind].forEach((r) => cards.push({ ...r, industry: ind }))
    })
  } else {
    ;(INDUSTRY_ROLES[selIndustry] || []).forEach((r) => cards.push({ ...r, industry: selIndustry }))
  }
  return cards
}

export function safeRolesForIndustry(selIndustry = 'all') {
  if (selIndustry === 'all') {
    const inds = Object.keys(SAFE_ROLES)
    return inds.map((ind) => SAFE_ROLES[ind]?.[0]).filter(Boolean).slice(0, 6)
  }
  return SAFE_ROLES[selIndustry] || []
}

